name: cro_holidays
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/ikaem/cro_holidays
homepage: https://github.com/ikaem/cro_holidays

environment:
  sdk: ^3.7.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
